version: "3"

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
  backend:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  db:
    build: ./db
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.10.3.2
    env_file:
      - ./development.env
  www:
    build: ./www
    ports:
      - 8080:80
    volumes:
      - ./www/src:/var/www/html/
    networks:
      backend:
        ipv4_address: 172.10.2.2
      frontend:
        ipv4_address: 172.10.1.2
    depends_on:
      - db
    env_file:
      - ./development.env